### ISSUE TITLE
Include https support

### ISSUE THREAD

**Issue by mandric** [jo/5984#1]
Would it be strange to include SSL support on this tool?  Was going to file a PR but thought I would ask first before writing any code.  This is useful if you have a CouchDB behind an SSL proxy.

Patching this file should do the trick to use `require('https')` instead of `require('http')` when we see https is the protocol in the URL:  https://github.com/jo/5984/blob/master/lib/request.js

**Comment by jo** [comment]
Yeah, thanks for reporting and your interest in 5984!

Will do as you proposed by now - in the future, I might switch over to using request.

**Comment by jo** [comment]
https://github.com/jo/5984/pull/2

**Comment by jo** [comment]
@mandric might I ask you to review that pull?

**Comment by mandric** [comment]
Done!

**Comment by jo** [comment]
Thank you @mandric!

**Comment by jo** [comment]
Released as [1.1.0](https://github.com/jo/5984/releases/tag/v1.1.0)
